export const PLATFORMS = {
  facebook: {
    name: 'Facebook',
    icon: 'logo-facebook',
    color: '#1877F2',
    envKey: 'FACEBOOK_APP_ID',
    description: 'Connect your Facebook page',
    scopes: [
      'pages_manage_posts',
      'pages_read_engagement',
      'pages_manage_engagement',
      'pages_show_list',
      'read_insights',
      'business_management',
    ],
  },
  instagram: {
    name: 'Instagram',
    icon: 'logo-instagram',
    color: '#E4405F',
    envKey: 'FACEBOOK_APP_ID',
    description: 'Connect your Instagram business account',
    scopes: [
      'instagram_basic',
      'instagram_content_publish',
      'instagram_manage_comments',
      'instagram_manage_insights',
    ],
  },
  twitter: {
    name: 'Twitter / X',
    icon: 'logo-twitter',
    color: '#1DA1F2',
    envKey: 'TWITTER_CLIENT_ID',
    description: 'Connect your Twitter account',
    scopes: [
      'tweet.read',
      'tweet.write',
      'users.read',
      'offline.access',
      'like.read',
      'like.write',
    ],
  },
  linkedin: {
    name: 'LinkedIn',
    icon: 'logo-linkedin',
    color: '#0A66C2',
    envKey: 'LINKEDIN_CLIENT_ID',
    description: 'Connect your LinkedIn organization',
    scopes: [
      'openid',
      'profile',
      'email',
      'w_member_social',
      'r_organization_social',
      'w_organization_social',
    ],
  },
  tiktok: {
    name: 'TikTok',
    icon: 'musical-notes',
    color: '#000000',
    envKey: 'TIKTOK_CLIENT_KEY',
    description: 'Connect your TikTok account',
    scopes: [
      'user.info.basic',
      'video.list',
      'video.upload',
      'video.publish',
    ],
  },
  pinterest: {
    name: 'Pinterest',
    icon: 'logo-pinterest',
    color: '#BD081C',
    envKey: 'PINTEREST_APP_ID',
    description: 'Connect your Pinterest account',
    scopes: [
      'boards:read',
      'boards:write',
      'pins:read',
      'pins:write',
      'user_accounts:read',
    ],
  },
  youtube: {
    name: 'YouTube',
    icon: 'logo-youtube',
    color: '#FF0000',
    envKey: 'GOOGLE_CLIENT_ID',
    description: 'Connect your YouTube channel',
    scopes: [
      'https://www.googleapis.com/auth/youtube',
      'https://www.googleapis.com/auth/youtube.upload',
      'https://www.googleapis.com/auth/youtube.force-ssl',
    ],
  },
};

export const PLATFORM_LIST = Object.keys(PLATFORMS);